### ISSUE TITLE
app failed to start with "npm start" command

### ISSUE THREAD

**Issue by gaurav341** [ui-router/sample-app-ng2#2] opened 2017-03-26 20:44 UTC
ERROR in /node_modules/preact/dist/preact.d.ts (52,28): ',' expected.
/node_modules/preact/dist/preact.d.ts (53,28): ',' expected.
/node_modules/preact/dist/preact.d.ts (52,22): Cannot find name 'keyof'.
/node_modules/preact/dist/preact.d.ts (52,45): Cannot find name 'Pick'.
/node_modules/preact/dist/preact.d.ts (53,22): Cannot find name 'keyof'.
/node_modules/preact/dist/preact.d.ts (53,84): Cannot find name 'Pick'.
webpack: Failed to compile.

**Comment by mat307** [comment] 2017-04-10 17:49
I am also having the same issue.

**Comment by hxrox** [comment] 2017-04-10 18:30
I am also having the same issue.

**Comment by yogichauhan** [comment] 2017-04-10 20:53
Same problem :(
<img width="836" alt="error" src="https://cloud.githubusercontent.com/assets/15213155/24882190/09082334-1df5-11e7-8e68-8a42dad8bf42.png">

**Comment by christopherthielen** [comment] 2017-04-22 21:04
Thanks for the reports.  This is caused by ui-router-visualizer which uses the `preact` library.  Preact added typings that are incompatible with typescript 2.0.x

Here's the related issue: https://github.com/developit/preact/issues/466#issuecomment-269458086

I'll see what can be done about this.  I believe angular 2.x doesn't support typescript 2.1.x and above.  I'll be updating this sample app to use angular 4.x ASAP

**Comment by christopherthielen** [comment] 2017-04-23 22:39
OK this is fixed now.  I've also updated the sample app to 1.0.0-beta.5

**Closed by christopherthielen** 2017-04-23 22:39 UTC
